// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xQ94SgPF7gilS7IMs6YtTpyxOK8sv-c',
    appId: '1:769491253471:web:934e271d6c1f8a3434516a',
    messagingSenderId: '769491253471',
    projectId: 'food-order-7bb20',
    authDomain: 'food-order-7bb20.firebaseapp.com',
    storageBucket: 'food-order-7bb20.appspot.com',
    measurementId: 'G-MS7G79VM7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8K5FQvtkzjPH_KimVIIrFw4bLoNVuaY',
    appId: '1:769491253471:android:4f6a30b3d2a5d50d34516a',
    messagingSenderId: '769491253471',
    projectId: 'food-order-7bb20',
    storageBucket: 'food-order-7bb20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4k9PndT2QqOY9OuEvYRw1iXPW6rd9H4',
    appId: '1:769491253471:ios:0bb7303523782a9234516a',
    messagingSenderId: '769491253471',
    projectId: 'food-order-7bb20',
    storageBucket: 'food-order-7bb20.appspot.com',
    iosClientId: '769491253471-5c39lc8jnddc2vksnd0e9g3ugv1kjte8.apps.googleusercontent.com',
    iosBundleId: 'com.example.FoodDeliveryUiPractice',
  );
}
